name: Docker Image CI

on:
  push:
   branches: [ master ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        echo "${{secrets.DOCKER_PASS}}" | docker login -u "vetonnshala" --password-stdin
        docker image build -t vetonnshala/dochub:lastes .
        docker push vetonnshala/dochub:lastes
